name: try build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: install depend
      run: sudo apt install libsqlite3-dev
    - name: clone submodule
      run: git submodule update --init --recursive
    - name: configure
      run: cmake .
    - name: make
      run: make
